# Site
name: 'Scott Morgan'
description: 'Personal site of Scott Morgan. Digital Lead at Bridgend College. Pages and blog about research based education, coding and technology. '
logo: 'assets/images/author.jpg'
#favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'smorgan@bridgend.ac.uk'
url: "https://scott3142.uk"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    scott:
      name:           Scott Morgan
      site:           https://scott3142.uk
      avatar:         assets/images/author-cropped.jpg
      bio:            "Head of Digital Innovation &amp; IT services at Bridgend College.<br> PhD in Mathematics.<br> Interested in education, coding and all things tech."
      email:          smorgan@bridgend.ac.uk
      twitter:        https://twitter.com/Scott3142

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: scott
      avatar: /assets/images/author-cropped.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
